#!/bin/bash
# =============================================================================
# MaruxOS 2.0.0 — 라이선스 준수 자료 생성 (ARM64 트랙)
#   ① SOURCES.md  : 빌드에 쓰인 모든 업스트림 tarball 목록 (이름·버전·크기·SHA256·출처 디렉토리)
#   ② patches/*.patch : 우리가 sed로 적용한 수정 사항을 **실제 트리 diff**로 추출 (GPL/LGPL 대응 소스 의무)
#   ③ $B/licenses/ : 이미지에 동봉할 라이선스 텍스트 수집 (config/licenses + tarball 내 COPYING)
# 실행: wsl -u root bash <this>   (빌드 아님 — 파일 생성만)
# =============================================================================
set -uo pipefail
B=/home/administrator/MaruxOS-arm64
LFS=$B/rootfs-clfs-arm64
WIN=/mnt/c/Users/Administrator/Desktop/MaruxOS
OUTP=$WIN/patches; mkdir -p "$OUTP" "$B/licenses"
SRC_MD=$WIN/SOURCES.md

# ---------- ① SOURCES.md ----------
echo "===== SOURCES.md ====="
{
  echo "# MaruxOS — Upstream sources (ARM64 2.0.0 build)"
  echo
  echo "Every binary in the image is built from the tarballs below (plus \`patches/\`). Generated by \`scripts/gen-sources-and-patches-arm64.sh\` on $(date +%F)."
  echo
  echo "| Tarball | Size | SHA256 | Where used |"
  echo "|---|---|---|---|"
  for d in "$LFS/sources" "$B/qt-src" "$B/fm-src" "$B/ed-src" "$B/tools-src" "$B/kernel"; do
    [ -d "$d" ] || continue
    find "$d" -maxdepth 1 -type f \( -name '*.tar.*' -o -name '*.tgz' -o -name '*.zip' -o -name '*.patch' \) 2>/dev/null | sort | while read -r f; do
      printf '| `%s` | %s | `%s` | %s |\n' "$(basename "$f")" "$(du -h "$f" | cut -f1)" "$(sha256sum "$f" | cut -c1-64)" "$(basename "$d")"
    done
  done
  echo
  echo "### Firmware (binary, redistributed unmodified)"
  echo
  for f in "$B"/firmware/*.elf "$B"/firmware/*.dat "$B"/firmware/*.bin "$LFS"/lib/firmware/brcm/brcmfmac43455-sdio.* "$LFS"/lib/firmware/regulatory.db; do
    [ -f "$f" ] && printf -- '- `%s` — %s — `%s`\n' "$(basename "$f")" "$(du -h "$f" | cut -f1)" "$(sha256sum "$f" | cut -c1-64)"
  done
  echo
  echo "### Firefox"
  echo
  [ -f "$LFS/opt/firefox/application.ini" ] && grep -E '^(Name|Version|BuildID)=' "$LFS/opt/firefox/application.ini" | sed 's/^/- /'
  echo "- Official Mozilla aarch64 ko build, unmodified (see THIRD-PARTY-LICENSES.md)."
} > "$SRC_MD"
echo "  $(grep -c '^| `' "$SRC_MD") tarballs → $SRC_MD"

# ---------- ② patches ----------
echo "===== patches ====="
mkpatch(){   # $1=출력명 $2=원본파일(.orig 또는 재전개본) $3=패치된 파일 $4=표시 경로
  if [ -f "$2" ] && [ -f "$3" ]; then
    diff -u --label "a/$4" --label "b/$4" "$2" "$3" > "$OUTP/$1"; rc=$?
    if [ $rc = 1 ]; then echo "  ✓ $1 ($(grep -c '^[+-][^+-]' "$OUTP/$1") 줄)"; else echo "  (동일/실패 rc=$rc) $1"; rm -f "$OUTP/$1"; fi
  else echo "  ⚠️ $1: 원본 또는 패치본 없음 ($2 / $3)"; fi
}
# 원본 확보: tarball을 임시 전개해서 해당 파일만 꺼낸다
TMP=$(mktemp -d)
extract_one(){ # $1=tarball $2=tar 내부 경로(최상위 디렉토리 제외, **정확한 경로**) → 경로 출력
  # (첫 판은 와일드카드 '*/CMakeLists.txt'가 하위 디렉토리 것을 먼저 집어 전체 diff가 나왔다 → 최상위 디렉토리를 실측해 정확히 지정)
  local tb="$1" inner="$2" top
  top=$(tar tf "$tb" 2>/dev/null | head -1 | cut -d/ -f1)
  tar xf "$tb" -C "$TMP" "$top/$inner" 2>/dev/null && echo "$TMP/$top/$inner"
}
# 빌드 트리가 이미 삭제된 패키지: tarball 원본에 install 스크립트와 **동일한 sed**를 적용해 패치본을 재구성
reapply(){ # $1=원본파일 → 패치본 경로 출력 ($2=sed 표현식...)
  local o="$1"; shift; local pdir; pdir=$(mktemp -d); cp "$o" "$pdir/f"; for e in "$@"; do sed -i "$e" "$pdir/f"; done; echo "$pdir/f"
}
K=$B/kernel/linux-6.18.26
KT=$(ls "$B"/kernel/linux-6.18.26.tar.* 2>/dev/null | head -1)
[ -n "$KT" ] && mkpatch linux-6.18.26-brcmfmac-disable-fwsup.patch "$(extract_one "$KT" drivers/net/wireless/broadcom/brcm80211/brcmfmac/feature.c)" "$K/drivers/net/wireless/broadcom/brcm80211/brcmfmac/feature.c" drivers/net/wireless/broadcom/brcm80211/brcmfmac/feature.c
# wpa_supplicant / ibus-hangul: 빌드 트리 삭제됨 → install 스크립트의 sed를 원본에 재적용해 diff (스크립트와 동일 표현식)
WT=$(ls "$LFS"/sources/wpa_supplicant-2.11.tar.* 2>/dev/null | head -1)
if [ -n "$WT" ]; then WO=$(extract_one "$WT" src/drivers/driver_nl80211_capa.c)
  WP=$(reapply "$WO" 's#capa->flags |= WPA_DRIVER_FLAGS_4WAY_HANDSHAKE_PSK;#(void)0; /* MaruxOS: host 4-way 강제 */#' 's#capa->flags |= WPA_DRIVER_FLAGS_4WAY_HANDSHAKE_8021X;#(void)0; /* MaruxOS: host 4-way 강제 */#')
  mkpatch wpa_supplicant-2.11-no-4way-offload.patch "$WO" "$WP" src/drivers/driver_nl80211_capa.c; fi
HT=$(ls "$LFS"/sources/ibus-hangul-1.5.5.tar.* 2>/dev/null | head -1)
if [ -n "$HT" ]; then HO=$(extract_one "$HT" src/engine.c)
  HP=$(reapply "$HO" 's|^    hangul->input_mode = input_mode;|    hangul->input_mode = input_mode; { FILE *mf = fopen ("/tmp/marux-ime-mode", "w"); if (mf != NULL) { fputs ((input_mode == INPUT_MODE_HANGUL) ? "han" : "eng", mf); fclose (mf); } }|')
  mkpatch ibus-hangul-1.5.5-export-input-mode.patch "$HO" "$HP" src/engine.c; fi
mkpatch glibc-2.38-math-vector-no-sve.patch "$LFS/usr/include/bits/math-vector.h.orig" "$LFS/usr/include/bits/math-vector.h" bits/math-vector.h
QT=$B/qt-src/qtbase-everywhere-src-5.15.2
mkpatch qtbase-5.15.2-mkspec-fortify2.patch "$(extract_one "$B/qt-src/qtbase-everywhere-src-5.15.2.tar.xz" mkspecs/linux-aarch64-gnu-g++/qmake.conf)" "$QT/mkspecs/linux-aarch64-gnu-g++/qmake.conf" mkspecs/linux-aarch64-gnu-g++/qmake.conf
XK=$QT/src/platformsupport/input/xkbcommon/qxkbcommon.cpp
[ -f "$XK" ] && mkpatch qtbase-5.15.2-xkb-keysyms.patch "$(extract_one "$B/qt-src/qtbase-everywhere-src-5.15.2.tar.xz" src/platformsupport/input/xkbcommon/qxkbcommon.cpp)" "$XK" src/platformsupport/input/xkbcommon/qxkbcommon.cpp
# <limits> 패치: 여러 헤더 — 트리 전체에서 'MaruxOS' 없이 '#include <limits>'가 1행인 파일을 찾아 묶음 diff
{ for f in $(grep -rl --include='*.h' --include='*.cpp' -m1 '^#include <limits>$' "$QT/src" 2>/dev/null | head -20); do
    rel=${f#$QT/}; o=$(extract_one "$B/qt-src/qtbase-everywhere-src-5.15.2.tar.xz" "$rel")
    [ -f "$o" ] && diff -u --label "a/$rel" --label "b/$rel" "$o" "$f"; done; } > "$OUTP/qtbase-5.15.2-gcc13-limits.patch"
[ -s "$OUTP/qtbase-5.15.2-gcc13-limits.patch" ] && echo "  ✓ qtbase-5.15.2-gcc13-limits.patch" || { echo "  ⚠️ limits 패치 비어있음"; rm -f "$OUTP/qtbase-5.15.2-gcc13-limits.patch"; }
QW=$B/qt-src/qtermwidget-0.17.0
[ -d "$QW" ] && mkpatch qtermwidget-0.17.0-optional-linguist.patch "$(extract_one "$B/qt-src/qtermwidget-0.17.0.tar.gz" CMakeLists.txt)" "$QW/CMakeLists.txt" CMakeLists.txt
QP=$B/tools-src/qps-1.10.20
[ -d "$QP" ] && mkpatch qps-1.10.20-allow-ascii-cast.patch "$(extract_one "$B/tools-src/qps-1.10.20.tar.xz" CMakeLists.txt)" "$QP/CMakeLists.txt" CMakeLists.txt
QH=$B/qt-src/qttools-everywhere-src-5.15.2/src/assistant/help
QHX=$LFS/usr/lib/cmake/Qt5Help/Qt5HelpConfigExtras.cmake
[ -f "$QH/Qt5HelpConfigExtras.cmake.in" ] && [ -f "$QHX" ] && { diff -u --label a/Qt5HelpConfigExtras.cmake --label b/Qt5HelpConfigExtras.cmake <(sed 's/@[A-Z_]*@/.../g' "$QH/Qt5HelpConfigExtras.cmake.in") "$QHX" > "$OUTP/qttools-5.15.2-help-config-no-hosttool-check.patch"; echo "  (참고) qttools help-config 패치: 설치본 대비 diff(템플릿 치환 무시)"; }
rm -rf "$TMP"
ls -la "$OUTP"

# ---------- ③ 라이선스 텍스트 수집 ----------
echo "===== licenses ====="
cp -f "$WIN"/config/licenses/* "$B/licenses/"
# tarball 안의 COPYING/LICENSE를 패키지명으로 저장 (있는 것만)
for tb in "$LFS"/sources/*.tar.* "$B"/qt-src/*.tar.* "$B"/fm-src/*.tar.* "$B"/ed-src/*.tar.* "$B"/tools-src/*.tar.*; do
  [ -f "$tb" ] || continue
  n=$(basename "$tb" | sed -E 's/\.tar\..*$//; s/-everywhere-src//')
  f=$(tar tf "$tb" 2>/dev/null | grep -E '^[^/]+/(COPYING|LICENSE|LICENCE|COPYING\.LIB|LICENSE\.txt|COPYING\.txt|COPYRIGHT)$' | head -1)
  [ -n "$f" ] || continue
  mkdir -p "$B/licenses/pkg/$n"; tar xf "$tb" -O "$f" > "$B/licenses/pkg/$n/$(basename "$f")" 2>/dev/null
done
echo "  공통 텍스트: $(ls "$B/licenses" | grep -v pkg | wc -l) / 패키지별: $(ls "$B/licenses/pkg" | wc -l)"
echo "GEN_OK"
